version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:019614656427:task-definition/webportal-task:1"
        LoadBalancerInfo:
          ContainerName: "webportal-container"
          ContainerPort: 80
        # Optional properties
        PlatformVersion: "LATEST"
        NetworkConfiguration:
            AwsvpcConfiguration:
              Subnets: ["subnet-143cc372", "subnet-5c997614"]
              SecurityGroups: ["sg-01fbf14f410e33e47"]
              AssignPublicIp: "ENABLED"