version: 0.2

env:
  CLOUDINARY_API_KEY: /webportal/CLOUDINARY_API_KEY
  CLOUDINARY_API_SECRET: /webportal/CLOUDINARY_API_SECRET
  CLOUDINARY_CLOUD_NAME: /webportal/CLOUDINARY_CLOUD_NAME
  DATABASE: /webportal/DATABASE
  PORT: /webportal/PORT

phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase ...
      - yum update -y
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - npm install
  pre-build:
    commands:
      - echo Entered the pre_build phase ...
  build:
    commands:
      - echo Entered the build phase ...
  post_build:
    commands:
      - echo Entered the post_build phase ...
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
