version: 0.2

env:
  parameter-store:
    CLOUDINARY_API_KEY: /webportal/CLOUDINARY_API_KEY
    CLOUDINARY_API_SECRET: /webportal/CLOUDINARY_API_SECRET
    CLOUDINARY_CLOUD_NAME: /webportal/CLOUDINARY_CLOUD_NAME
    DATABASE: /webportal/DATABASE
    PORT: /webportal/PORT

phases:
  install:
    run-as: root
    runtime-versions:
      nodejs: 10
    commands:
      - echo Entered the install phase ...
      - yum update -y
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
      - npm install
  pre_build:
    run-as: root
    commands:
      - echo Entered the pre_build phase ...
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    run-as: root
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...
      - echo Building the Docker image...       
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG    
  post_build:
    run-as: root
    commands:
      - echo Entered the post_build phase ...
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - "**/*"
